# 
#   _config.yml
# 

title : 立命館大学 物理科学研究会 公式HP
short_title: 物理科学研究会
author: 立命館大学物理科学研究会
copyright: 2019-2021 立命館大学 物理科学研究会
keywords: 立命館大学, 物理科学研究会
description: >- # this means to ignore newlines until "baseurl:"
  立命館大学物理科学研究会の公式ホームページです。
  物理科学研究会は、立命館大学BKCにて、物理学を中心として科学全般についての研究活動を行っている学友会学術部公認のサークル団体です。
  このホームページでは日々の活動や、各部員の研究成果をまとめた「会誌」の公開などをしています。
baseurl: "" # the subpath of your site, e.g. /blog
url    : "http://vuccaken.github.io" # the base hostname & protocol for your site, e.g. http://example.com

social:
  email  : vuccaken@gmail.com
  twitter: vuccaken
  github : vuccaken
  youtube: UCKO7a5YVCnFAquUzLKeIrMg


collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "page"
      toc: true


## 変換対象から除外
exclude:
  - .github/
  - .vscode/
  - .gitignore
  - bs-config.js
  - Gemfile
  - Gemfile.lock
  - Makefile
  - Procfile
  - README.md
  - setup.sh
  # ## 以下も除外しないとGitHub Actionsでエラーが出る
  # - node_modules
  # - vendor/bundle/
  # - vendor/cache/
  # - vendor/gems/
  # - vendor/ruby/

plugins:
  - jekyll-tidy
